name: Performance Tests
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run local JMeter test
        run: npm run test:local
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-reports
          path: jmeter/reports
